#include <stdio.h>
#include <stdlib.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

// Max files is something ridiculous
#define MAX_FILES 2000

int scandir(const char* dir, const char** files, int* count)
{
    DIR* d = opendir(dir);
    struct dirent* e;
    
    if(!d)
    {
        printf("ERROR: Could not open directory %s!\n", dir);
        
        return 0;
    }
    
    while((e = readdir(d)) != NULL)
    {
        if(
            strcmp(".", e->d_name) == 0
            ||
            strcmp("..", e->d_name) == 0
        )
        {
            continue;
        }
        
        char* filename = malloc(sizeof(char) * (strlen(dir) + strlen(e->d_name) + 1));
        sprintf(filename, "%s/%s", dir, e->d_name);
        
        struct stat p;
        stat(filename, &p);
        
        if(S_ISREG(p.st_mode))
        {
            files[*count] = filename;
            
            (*count)++;
        }
        else
        {
            scandir(filename, files, count);
        }
    }
    
    closedir(d);
    
    return 1;
}

int main(int argc, char* argv[])
{
    char* dir = ".";
    char* includesFilename = "includes.c";
    
    for(int i = 1; i < argc; i++)
    {
        dir = argv[i];
    }
    
    const char** files = malloc(sizeof(void*) * MAX_FILES);
    int count = 0;
    
    scandir(dir, files, &count);
    
    int incstrlen = 0;
    int incstrlencount = 0;
    int linecount = 0;
    
    for(int i = 0; i < count; i++)
    {
        incstrlen += 12 + strlen(files[i]);
    }
    
    char* incstr = malloc(sizeof(char) * (incstrlen + 1));
    
    for(int i = 0; i < count; i++)
    {
        linecount = 12 + strlen(files[i]);
        
        sprintf(&incstr[incstrlencount], "#include \"%s\"\n", files[i]);
        
        incstrlencount += linecount;
    }
    
    incstr[incstrlencount] = '\0';
    
    // THIS USES WRITE, NOT APPEND!
    // YOU WILL LOSE WORK IF YOU HAVE CUSTOM CODE IN YOUR INCLUDE FILE!!!
    // You should, for example, have a separate file for autogenerated includes,
    // Then if you need custom-written includes, put those in another file
    FILE* inc = fopen(includesFilename, "w");
    fprintf(inc, "%s", incstr);
    fclose(inc);
    
    // Not freeing memory here
    // Maybe I should
    
    return 0;
}
